title: Akeem Babalola
description: Postgraduate study in Economics and Big Data & Business Intelligence complementing my professional experience in pricing and data analysis. A keen eye and confident communicator pursuing a position in quantitative analysis and research with domain experience in energy, finance, health and music.   
#show_downloads: false
theme: jekyll-theme-minimal
