title: Akeem Babalola
description: Data Analytics and Business Intelligence professional with postgraduate expertise in Economics and Big Data & Business Intelligence, experienced in predictive analytics, pricing intelligence, machine learning, business intelligence reporting, and data-driven decision-making across the energy, finance, health, technology, and media sectors.  
#show_downloads: false
theme: jekyll-theme-minimal
