title: Akeem Babalola
logo: /assets/1676883529372.jpeg
description: MSc Big Data and Business Intelligence | Seeking opportunities as a Data Analyst or Scientist
#show_downloads: false
theme: jekyll-theme-minimal
