title: Akeem Babalola
description: MSc Big Data and Business Intelligence | Seeking a position within a domain of interest; health, finance and governance.   
#show_downloads: false
theme: jekyll-theme-minimal
